### ISSUE TITLE
artifactoryPublish does not properly report 409 Conflict response

### ISSUE THREAD

**Issue by javabrett** [JFrogDev/build-info#140]
id 'com.jfrog.artifactory' version '4.5.4'

Artifactory OSS
4.6.1 rev 40143

Due to a misconfiguration, a plugin was attempting to push a RELEASE artifact to a repo with SNAPSHOT policy.

Expectation: it should be possible to read the error from the Gradle build, even if `--stacktrace` or `--debug` is required.

Actual: Need to visit Artifactory logs.  Plugin seems to get a mix of 409 and 100 CONTINUE responses, then ends-up with a socket disconnection when Artifactory hangs-up, which is all that is reported to Gradle.  There is certainly at least one 409 response:

```

HTTP/1.1 409 Conflict
Server: Artifactory/4.6.1
X-Artifactory-Id: 0a8f3fc214bd62e2:-42ca8f5a:15f67e211ea:-8000
Content-Type: application/json;charset=ISO-8859-1
Transfer-Encoding: chunked
Date: Tue, 28 Nov 2017 23:26:20 GMT

{
  "errors" : [ {
    "status" : 409,
    "message" : "The repository '<REDACTED>' rejected the artifact '<REDACTED>' due to its snapshot/release handling policy."
  } ]
}HTTP/1.1 100 Continue

```

Artifactory logs shows similar.  Gradle stacktrace is:

```
> Task :artifactoryPublish
Deploying artifact: <redacted>
Error occurred for request PUT <redacted> HTTP/1.1: Connection reset.
Attempting retry #1
Error occurred for request PUT <redacted> HTTP/1.1: Connection reset.
Attempting retry #2
Error occurred for request PUT <redacted> HTTP/1.1: Connection reset.
Attempting retry #3
Error occurred for request PUT <redacted> HTTP/1.1: Connection reset.

Caused by: java.net.SocketException: Connection reset
        at org.apache.http.impl.io.SessionOutputBufferImpl.streamWrite(SessionOutputBufferImpl.java:124)
        at org.apache.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:136)
        at org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:167)
        at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:113)
        at org.apache.http.entity.FileEntity.writeTo(FileEntity.java:99)
        at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156)
        at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:162)
        at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.execchain.ServiceUnavailableRetryExec.execute(ServiceUnavailableRetryExec.java:84)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.jfrog.build.client.PreemptiveHttpClient.execute(PreemptiveHttpClient.java:103)
        at org.jfrog.build.client.ArtifactoryHttpClient.execute(ArtifactoryHttpClient.java:216)
        at org.jfrog.build.client.ArtifactoryHttpClient.upload(ArtifactoryHttpClient.java:212)
        at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.uploadFile(ArtifactoryBuildInfoClient.java:654)
        at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.deployArtifact(ArtifactoryBuildInfoClient.java:344)
        at org.jfrog.gradle.plugin.artifactory.task.BuildInfoBaseTask.deployArtifacts(BuildInfoBaseTask.java:534)
        at org.jfrog.gradle.plugin.artifactory.task.BuildInfoBaseTask.prepareAndDeploy(BuildInfoBaseTask.java:453)
        at org.jfrog.gradle.plugin.artifactory.task.BuildInfoBaseTask.collectProjectBuildInfo(BuildInfoBaseTask.java:129)
        at org.jfrog.gradle.plugin.artifactory.task.BuildInfoBaseTask.taskAction(BuildInfoBaseTask.java:116)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        ... 114 more

```
Possible this is a shortcoming of should-I-retry logic in `PreemptiveHttpClient` `getNonRetriableClasses()`.

**Comment by eyalbe4** [comment]
Thanks for reporting this @javabrett.
We'll look into this soon and update with our findings.

**Comment by romangurevitch** [comment]
@javabrett,
We are trying to reproduce this issue but we can't see the logs you are getting.
We are running one of our basic gradle examples: [gradle-example](https://github.com/JFrogDev/project-examples/tree/master/gradle-examples/4/gradle-example), 
after changing target repository to `libs-release-local` we can see the following output: 

```
What went wrong:
Execution failed for task ':shared:artifactoryPublish'.
> java.io.IOException: Failed to deploy file. Status code: 409 Response message: Artifactory returned the following errors: 
  The repository 'libs-release-local' rejected the resolution of an artifact 'libs-release-local:org/jfrog/example/gradle/api/1.0-SNAPSHOT/api-1.0-SNAPSHOT-javadoc.jar' due to conflict in the snapshot release handling policy. Status code: 409
```

Could you run this example and let us know if you see the issue in your logs?

**Comment by javabrett** [comment]
I agree - I ran the example against OSS 5.6.2 and the results were perfect as you found.  So I will have to put this down to the much older OSS from the report, or something else to do with that environment.

Closing - thanks for checking.

**Comment by nfalco79** [comment]
We got the same issue on artifactory 6.5.8

```
[INFO] Deploying artifact: https://acme.finantix.com/artifactory/ext-snapshot-local/org/owasp/dependency-check-maven/5.0.0-M1/dependency-check-maven-5.0.0-M1.jar
[ERROR] org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded() listener has failed: 
java.lang.RuntimeException: Error occurred while publishing artifact to Artifactory: /var/lib/jenkins/jobs/DependencyCheck/workspace/maven/target/dependency-check-maven-5.0.0-M1.jar.
 Skipping deployment of remaining artifacts (if any) and build info.
	at org.jfrog.build.extractor.maven.BuildDeploymentHelper.deployArtifacts(BuildDeploymentHelper.java:303)
	at org.jfrog.build.extractor.maven.BuildDeploymentHelper.deploy(BuildDeploymentHelper.java:103)
	at org.jfrog.build.extractor.maven.BuildInfoRecorder.sessionEnded(BuildInfoRecorder.java:173)
	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:64)
	at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:42)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:137)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.jvnet.hudson.maven3.launcher.Maven33Launcher.main(Maven33Launcher.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at jenkins.maven3.agent.Maven33Main.launch(Maven33Main.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:139)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:70)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Failed to deploy file. Status code: 409 Response message: Artifactory returned the following errors: 
The repository 'ext-snapshot-local' rejected the resolution of an artifact 'ext-snapshot-local:org/owasp/dependency-check-maven/5.0.0-M1/dependency-check-maven-5.0.0-M1.jar' due to conflict in the snapshot release handling policy. Status code: 409
	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.uploadFile(ArtifactoryBuildInfoClient.java:692)
	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.doDeployArtifact(ArtifactoryBuildInfoClient.java:374)
	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.deployArtifact(ArtifactoryBuildInfoClient.java:362)
	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.deployArtifact(ArtifactoryBuildInfoClient.java:347)
	at org.jfrog.build.extractor.maven.BuildDeploymentHelper.deployArtifacts(BuildDeploymentHelper.java:300)
	... 30 more
```
