### ISSUE TITLE
Log verbosely in exception cases within ArtifactoryHttpClient.execute

### ISSUE THREAD

**Issue by xasx** [JFrogDev/build-info#65]
We are currently facing errors like:

```
[ERROR] Failed while reading the response from: PUT https://my.server.address/artifactory/myrepo/org/mynamespace/myartifact/1.0-2015-10-01-r285d831d/myartifact-1.0-2015-10-01-r285d831d.war;vcs.revision=285d831dd064851bb5ef3df45d69b3ee097f3a68;build.timestamp=1443688654812;build.name=Build-My-Artifact;build.number=4711 HTTP/1.1
org.codehaus.jackson.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.StringReader@7759203a; line: 1, column: 2]
	at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:943)
	at org.codehaus.jackson.impl.JsonParserBase._reportError(JsonParserBase.java:632)
	at org.codehaus.jackson.impl.JsonParserBase._reportUnexpectedChar(JsonParserBase.java:565)
	at org.codehaus.jackson.impl.ReaderBasedParser._handleUnexpectedValue(ReaderBasedParser.java:429)
	at org.codehaus.jackson.impl.ReaderBasedParser.nextToken(ReaderBasedParser.java:192)
	at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:1625)
	at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:1560)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:711)
	at org.codehaus.jackson.JsonParser.readValueAs(JsonParser.java:879)
	at org.jfrog.build.client.ArtifactoryHttpClient.execute(ArtifactoryHttpClient.java:209)
	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.tryChecksumDeploy(ArtifactoryBuildInfoClient.java:649)
	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.uploadFile(ArtifactoryBuildInfoClient.java:607)
	at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.deployArtifact(ArtifactoryBuildInfoClient.java:330)
```

But we are totally unable to track it down since uploads within the same build also succeed.

In order to be able to track the issues down (to whatever they may be), it would be helpful if there was some kind of verbose logging that shows the response that is being returned by the server.

Perhaps logging the `content` whithin `ArtifactoryHttpClient.execute` at a certain logging level is feasible here. I would consider it even more helpful than the stacktrace.

**Comment by eyalbe4** [comment]
Thanks @xasx. We will see how we can log this. There's a chance the response the client gets in this case is an HTML from the web proxy, or even from Artifactory if it is in the process of starting up.
.

**Comment by xasx** [comment]
@eyalbe4 Thanks. 

Yes, HTML is what I assume as well. My suspect is the underlying Tomcat that presents an error page. But there's not even an error code logged so it's only assumptions I can make here.

**Comment by c5157248** [comment]
Hi,
We are facing exactly the same problem so I was wondering if there are any insights about it.
The problem started after upgrading to Artifactory Plugin version 2.2.4 to  2.3.1.

**Comment by AlexeiVainshtein** [comment]
Hi All

I would like to update that this issue for adding additional information to the log is currently work in progress.

**Comment by xasx** [comment]
:+1:

**Comment by eyalbe4** [comment]
@AlexeiVainshtein 's [pull request](https://github.com/JFrogDev/build-info/pull/71) for logging HTML responses has just been merged.
Thanks @AlexeiVainshtein!
[This Jira issue](https://www.jfrog.com/jira/browse/BI-324) tracks this code change.
